### ISSUE TITLE
The add-on's helper is not compatible with Ember 1.11.x

### ISSUE THREAD

**Issue by Ky6uk** [ivanvotti/ember-svg-jar#11]
I am not sure, but it looks like module doesn't work with Ember `v1.11.3`. Should he?

![screen shot 2016-07-27 at 00 04 34](https://cloud.githubusercontent.com/assets/46930/17155511/16cb9c44-538e-11e6-821b-39f3f2408046.png)

![screen shot 2016-07-27 at 00 05 07](https://cloud.githubusercontent.com/assets/46930/17155510/16c8d2c0-538e-11e6-98dc-f5182bb07dd4.png)

**Comment by ivanvotti** [comment]
At the moment the addon requires Ember 1.13 and beyond to work. But there's no big reason for that. I'm going to find a way to make it work even with old Ember versions.

**Comment by ivanvotti** [comment]
Fixed it in the latest release. Please try it and let me know if you still have any problems with it.

`ember-svg-jar` v0.8.0 is compatible with Ember 1.10.1 and beyond.
