### ISSUE TITLE
Some icons are broken by optimization. 

### ISSUE THREAD

**Issue by iand675** [ivanvotti/ember-svg-jar#113]
The feather icon set in particular has several instances where this happens. One example is the help-circle icon: 
![image](https://user-images.githubusercontent.com/69209/49197217-6f8c9a00-f3d1-11e8-87fc-7d49d524a965.png)

It seems to be where a line starts and stops at the same point that it is removed:

``` xml
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" 
viewBox="0 0 24 24" 
fill="none" 
stroke="currentColor" 
stroke-width="2" 
stroke-linecap="round" 
stroke-linejoin="round" 
class="feather feather-help-circle">
  <circle cx="12" cy="12" r="10"></circle>
  <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"></path>
  <line x1="12" y1="17" x2="12" y2="17"></line>
</svg>
```

**Comment by ivanvotti** [comment]
Try to optimize your icon with [svgomg ](https://jakearchibald.github.io/svgomg/), playing with different features. This way you can find plugins that cause the issue. Then you could just disable problem plugins like this:
```js
svgJar: {
  optimizer: {
    plugins: [
      { cleanupIDs: false }
    ]
  }
}
```
