### ISSUE TITLE
Docs: build and svg inclusions

### ISSUE THREAD

**Issue by edeis53** [ivanvotti/ember-svg-jar#114]
I'm not quite clear from the docs on how svg-jar works in regards to which svg are included with the build.

If I specify in the `ember-cli-build.js`
```
    svgJar: {
      sourceDirs: [
        "public/images/icons",
        "node_modules/material-design-icons/navigation/svg/production" 
      ]
    }
```

Will ALL the icons found in these folders be included in my app when built? 

or does svg-jar works some kind of magic, and only includes icons that it's found used in my app via the helpers `{{svg-jar "material-design-asset-name"}}`.

Say I only want to use one icon from the material design set? what to do in that circumstance?

**Comment by ivanvotti** [comment]
Unfortunately, all the icons found in `sourceDirs` will be included regardless of which of them you actually use in your templates. At the moment to use just one icon you have to put it to any folder that is in the `sourceDirs`.
