### ISSUE TITLE
linearGradient shared unless cleanupIDs is manually disabled 

### ISSUE THREAD

**Issue by samselikoff** [ivanvotti/ember-svg-jar#115]
The `cleanupIDs` SVGO plugin is not working properly, perhaps because it doesn't have all the files at the time it autogenerates new ids. I was seeing some behavior where two `<linearGradient>` definitions were both getting rewritten to have `id="a"` (by SVGO), and thus all SVGs using gradients were getting the same one.

I fixed this for now by disabling the plugin in `ember-cli-build.js`

```js
svgJar: {
  optimizer: {
    plugins: [
      { cleanupIDs: false }
    ]
  }
}
```

but I wonder if the way we're loading SVG assets & handing them over to SVGO is preventing it from cleaning things up correctly.

**Comment by ivanvotti** [comment]
According to [this issue](https://github.com/svg/svgo/issues/674) it's related to the way `cleanupIDs` plugin works. There you can find at least two possible solutions:
```js
svgJar: {
  optimizer: {
    plugins: [
      {
        cleanupIDs: {
          prefix: {
            toString() {
              this.counter = this.counter || 0;
              return `id-${this.counter++}`;
            }
          }
        }
      }
    ]
  }
}
```

Or just:
```js
svgJar: {
  optimizer: {
    plugins: [
      { cleanupIDs: { minify: false } }
    ]
  }
}
```

**Comment by samselikoff** [comment]
Cool - thanks Ivan!
