### ISSUE TITLE
Un-hashified files in dist/assets

### ISSUE THREAD

**Issue by markcatley** [ivanvotti/ember-svg-jar#124]
Hi,

On crates.io we put a far future expire header (10 years) for all resources in our `dist/assets` folder - ember places all other images into `dist/assets` with a hash in the filename so that if the images are updated the cache is invalidated. It appears that SVGs only used with ember-svg-jar get placed into `dist/assets` without a hash, but then are not used.

What are the options for either:
1. Preventing the SVGs from being placed in dist/assets; or
2. Ensuring the SVGs get an appropriate hash in their filename.

The tracking issue in crates.io is rust-lang/crates.io#1575.

Thank you,
Mark

**Comment by ivanvotti** [comment]
`ember-svg-jar` only reads all the SVGs you have in your `sourceDirs` (by default it's `public`). It doesn't affect how your SVGs will be processed by `ember-cli` or other addons. It doesn't try to prevent anything.

The second option can be done with `fingerprint`. You just need to add `svg` to the `extensions` array. Here is an example `ember-cli-build.js`:
```
    fingerprint: {
      extensions: ['js', 'css', 'png', 'jpg', 'gif', 'map', 'svg', 'ttf', 'woff', 'woff2'],
    }
```

Does it work for you?

**Comment by markcatley** [comment]
Thanks @ivanvotti, works perfectly. Is there any value in me doing a documentation PR for anyone in the future?

**Comment by ivanvotti** [comment]
Sure, that would be helpful. We could add `Troubleshooting` section at the end of the `README` file or as a separate file in [docs](https://github.com/ivanvotti/ember-svg-jar/tree/master/docs) directory.
