### ISSUE TITLE
No ability to use helper outside template (i.e. in route or component)

### ISSUE THREAD

**Issue by djsegal** [ivanvotti/ember-svg-jar#14]
I'd like to use svg-jar for all svg purposes.

Can you make the helper available outside just templates

**Comment by ivanvotti** [comment]
Can you please give me an example how would you use it in your routes or components?

**Comment by djsegal** [comment]
```
    ...
    var textDiv = document.createElement('div');
    textDiv.innerHTML = "<div>..." + svgJar("logo") + "...</div>";
    ...
    widget.options = {
        text: textDiv
    };
    ...
```

**Comment by djsegal** [comment]
you can now add it to a route using something like:

+ `import { svgJar } from '../helpers/svg-jar';`
