### ISSUE TITLE
Viewer: screen width problems with SVG list

### ISSUE THREAD

**Issue by tcjr** [ivanvotti/ember-svg-jar#140]
#### Describe the bug

In the viewer, the SVGs don't always show up depending on the screen width.

#### Reproduce the bug

See gif below.

#### Expected behavior

Everything, all the time.

#### Screenshots

![svgjar](https://user-images.githubusercontent.com/142243/65834097-1e715f00-e29d-11e9-80a1-b4cf003559fc.gif)

#### Additional context

Version 2.2.2
I have 14 SVGs in my project.

**Comment by ivanvotti** [comment]
Good catch, thanks. I just fixed it and will publish it today.
@all-contributors please add @tcjr for bug

**Comment by ivanvotti** [comment]
The issue should be fixed in `v.2.2.3`. Feel free to reopen it if you still can reproduce it.
