### ISSUE TITLE
Can't install addon directly from github repo

### ISSUE THREAD

**Issue by djsegal** [ivanvotti/ember-svg-jar#15]
```
>>>> ember serve
Cannot find module './lib/index'
Error: Cannot find module './lib/index'
  at Function.Module._resolveFilename (module.js:339:15)
  at Function.Module._load (module.js:290:25)
  at Module.require (module.js:367:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/Users/djsegal/code/project/node_modules/ember-svg-jar/index.js:1:80)
```

**Comment by djsegal** [comment]
This only happens when I install the addon from github, i.e. through:

+ `ember install https://github.com/ivanvotti/ember-svg-jar`

**Comment by ivanvotti** [comment]
The addon is not supposed to be installed from the GitHub repo directly. You need to install it from the NPM registry.

There's a  build step that is required to get a working npm package and you can find it in the README: `npm run build`. Also when I publish the NPM package I build the viewer into the `public` directory.

**Comment by djsegal** [comment]
Ok, sounds good. Thanks for the quick reply
