### ISSUE TITLE
can't copy helper code nor svg contnet 

### ISSUE THREAD

**Issue by nagi1** [ivanvotti/ember-svg-jar#157]
#### Describe the bug

On fresh install of ember and ember-svg-jar, I cant seem to copy any helper code nor svg contnet from the viewer.

#### Reproduce the bug

clean fresh install then yarn start

#### Expected behavior

to copy svg content.
nothing happen when I click copy or copy svg contnet.

#### Additional context

[Demo](https://svgjar.web.app) project is down!

**Comment by ivanvotti** [comment]
Feel free to reopen if you still have the problem.

**Comment by nagi1** [comment]
- I can copy from the demo app.
- I'm using the latest version of firebox.
- the demo app was down for a couple of days.

I still have the weird problem, with totally fresh untouched installation where I can't copy icons.

```bash
$ ember -v
ember-cli: 3.17.0
node: 10.19.0
os: win32 x64
```

**Comment by ivanvotti** [comment]
It's probably related to the OS you use. Windows support is still not good as I don't have windows and enough time to support it. Anyway, it would be helpful to have a repo reproducing the issue.
