### ISSUE TITLE
Import `htmlSafe` from `@ember/template` not `@ember/string`

### ISSUE THREAD

**Issue by wagenet** [ivanvotti/ember-svg-jar#171]
#### Describe the bug

When used with Ember Beta 3.25 the following deprecation warning is visible:

```
Importing htmlSafe from '@ember/string' is deprecated. Please import htmlSafe from '@ember/template' instead.
```

**Comment by rwwagner90** [comment]
This is going to be an issue for addons. @wagenet is there a recommended way to support both latest Ember and older versions?

**Comment by wagenet** [comment]
@rwwagner90 According to the docs, `@ember/template` was introduced in 3.8. Personally, I would have no qualms about new package releases not supporting that far back, especially given that the oldest LTS is is 3.16.

**Comment by rwwagner90** [comment]
Thanks for that clarity @wagenet, I agree.
