### ISSUE TITLE
Cannot load ember-svg-jar with Ember 1.13

### ISSUE THREAD

**Issue by tastycode** [ivanvotti/ember-svg-jar#18]
According to the README,`svg-jar` should be compatible with Ember 1.13. `UI.writeWarnLine` was not added until after Ember 2.2.0-beta1 (https://github.com/ember-cli/ember-cli/commit/139975c9ce169fef62e71b2b54972836f0f6edaa#diff-862010a5cfb735a85ea8db20df2b584fR113), and is used from this commit. https://github.com/ivanvotti/ember-svg-jar/commit/8ee9e8459f2d4c8244d4d0770bb4e5df7e87a1f3#diff-8ffd6f3f3d19b1908dc104c8e5b486d0R54. 

What is the latest version of svg-jar that is still compatible with Ember 1.13?

**Comment by ivanvotti** [comment]
`UI.writeWarnLine` is a feature of ember-cli. You need to upgrade you `ember-cli`, to use the addon. The README is correct, SVGJar is compatible with Ember 1.13

**Comment by ivanvotti** [comment]
Closing for now. Please feel free to reopen, if you still have any questions regarding the issue.
