### ISSUE TITLE
SVG Browser does not load when app rootURL is configured

### ISSUE THREAD

**Issue by wireframe** [ivanvotti/ember-svg-jar#22]
My ember application is configured w/ an alternate `rootUrl`.  

ex:
```javascript
// config/environment.js
var ENV = {
  environment,
  rootURL: '/frontend/'
}
```

When I load up the svg viewer site, it errors out attempting to load all the ember-svg-jar assets without using the rootUrl prefix.
URL: http://localhost:4200/frontend/ember-svg-jar/index.html

attempts to load content from:
Requested URL: http://localhost:4200/ember-svg-jar/assets/vendor.css

If I remove the rootURL from my application config, the ember-svg-jar site loads as expected.

**Comment by alexnj** [comment]
Thanks so much for providing this addon.

Would this issue be fixed? Not able to use with any app that has `rootURL` configured. :(

**Comment by ivanvotti** [comment]
Can you create an ember app to reproduce the issue, so I can run it?

**Comment by mrkirchner** [comment]
@ivanvotti Here you go https://github.com/mrkirchner/ember-svg-jar-root

Once Ember Serve is going got to:
http://localhost:4200/home/ember-svg-jar/index.html

**Comment by ivanvotti** [comment]
@mrkirchner Thanks, I'll take a look at it soon.

**Comment by ivanvotti** [comment]
The issue is fixed. I'll release today.
