### ISSUE TITLE
SVG stroke/fill rendering issue

### ISSUE THREAD

**Issue by jakeleboeuf** [ivanvotti/ember-svg-jar#23]
Just got things setup and seeing a really odd fill/stroke rendering bug. I'm assuming this is exposing some inconsistency with my `.svg` files, but I'm confused with why I'de be seeing this flicker when selecting between icons?

![svg-jar](https://cloud.githubusercontent.com/assets/690573/20851724/0c80ccf0-b8b0-11e6-9a25-ca50ddce6d80.gif)

**Comment by ivanvotti** [comment]
That looks weird. I had a similar problem when my SVG file was incorrect. I have no idea what's going on here. Closing for now.

**Comment by ivanvotti** [comment]
Related to https://github.com/ivanvotti/ember-svg-jar/issues/68
