### ISSUE TITLE
Does not find assets in addon

### ISSUE THREAD

**Issue by rwwagner90** [ivanvotti/ember-svg-jar#29]
I would love to see this find things in `tests/dummy/public` as well.

**Comment by knownasilya** [comment]
Yes, please!

**Comment by rwwagner90** [comment]
@knownasilya do you have any idea how we might do that? Perhaps we could collaborate on implementing this.

**Comment by knownasilya** [comment]
Well, I did have a quick look last night, and it doesn't seem like there is a `treeForDummyPublic`, so I'd probably ask one of the cli experts @stefanpenner @rwjblue @Turbo87

**Comment by jeanduplessis** [comment]
I might be missing the issue but I got it to read svgs from my `tests/dummy/public` directory by setting the following in `ember-cli-build.js` of my addon:

```javascript
let app = new EmberAddon(defaults, {
    svgJar: {
      strategy: 'inline',
      sourceDirs: ['tests/dummy/public']
    }
  });
```

**Comment by rwwagner90** [comment]
@jeanduplessis yes, that does work, but the idea is that it would work automatically. Perhaps we could just add that if in an addon. I'll take a look.
