### ISSUE TITLE
Support icons that are added at build time

### ISSUE THREAD

**Issue by ssylvia** [ivanvotti/ember-svg-jar#34]
There are a couple addons that allow you to include node assets which get copied to the public/vendor folders at runtime:
https://github.com/dfreeman/ember-cli-node-assets
https://github.com/kellyselden/ember-cli-node-modules-to-vendor

It would be great if that SVG linked in these npm repos would get added to the SVG jar so all available icons can be easily referenced by developers.

**Comment by ivanvotti** [comment]
@ssylvia `ember-svg-jar` does allow you to get icons from `node_modules`. Here is an example with `material-design-icons`, a random npm package I just found to show how it works:

`$ npm install material-design-icons`

`ember-cli-build.js`:
```js
// ...
module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
	svgJar: {
	    sourceDirs: ['node_modules/material-design-icons']
	}
  });
// ...
```
So this way you can include any node assets that are SVGs. Please let me know if it solves the issue so we can close it.

**Comment by ivanvotti** [comment]
@ssylvia `ember-svg-jar` does allow you to get icons from `node_modules`. Here is an example with `material-design-icons`, a random npm package I just found to show how it works:

`$ npm install material-design-icons`

`ember-cli-build.js`:
```js
// ...
module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
	svgJar: {
	    sourceDirs: ['node_modules/material-design-icons']
	}
  });
// ...
```
So this way you can include any node assets that are SVGs. Please let me know if it solves the issue so we can close it.

**Comment by ssylvia** [comment]
Perfect, thanks.
