### ISSUE TITLE
Feature request: Add external SVGO respository

### ISSUE THREAD

**Issue by marcelotedeschi** [ivanvotti/ember-svg-jar#38]
Hi there, I was wondering if it is possible to add an option to use an external svgo respository, so that our own plugins can be used.

**Comment by ivanvotti** [comment]
It can be done ([like this](https://github.com/ivanvotti/ember-svg-jar/blob/master/docs/configuration.md#optimizer-can-be-redefined-on-a-strategy-level)):
```js
{
  svgJar: {
    optimizer : {
      svgoModule: require('svgo')
    }
  }
}
```
