### ISSUE TITLE
Provide option to add a11y tags to svg.

### ISSUE THREAD

**Issue by ssylvia** [ivanvotti/ember-svg-jar#43]
Here's blog post that has tips for making svg's more accessible: https://www.sitepoint.com/tips-accessible-svg/.

Not sure if it should be a single argument object (since the addon parses the rest as normal attributes for the top level svg tag https://github.com/ivanvotti/ember-svg-jar/blob/master/addon/utils/make-svg.js#L7), or if you'd rather want each one as an individual options and then parse out what you need.

Example:
```hbs
{{ svg-icon "share" a11y=a11yObject }}
```
or 

```hbs
{{ svg-icon "share" a11yTitle="Share" a11yDesc="Share link on social media" ... }}
```

It would also be really nice if the title/desc id's we're generated by default if an argument was not passed for them.

**Comment by GCheung55** [comment]
How about individual properties without the `a11y` prefix. They can basically just be:

* title
* desc
* role
* text
