### ISSUE TITLE
Symbol strategy doesn't work on Windows

### ISSUE THREAD

**Issue by ghost** [ivanvotti/ember-svg-jar#46]
I'm on Windows 10, latest ember, latest ember-data, latest ember-svg-jar.

My `ember-cli-build.js`:

```
module.exports = function (defaults) {
  let app = new EmberApp(defaults, {
    fingerprint: {
      exclude: ['assets/images']
    },
    svgJar: {
      strategy: 'symbol',
      symbol: {
        sourceDirs: ['vendor/icons']
      }
    }
  });
```

This in my .hbs: `{{svg-jar "news"}}`

![image](https://user-images.githubusercontent.com/21275217/29755330-c73933c0-8b96-11e7-8f4f-573883855821.png)

As you can see it is looking for "http://localhost:4200/assetssymbols.svg". But also if I copy the correct "symbols.svg" file in `public/` and then rename it in `assetssymbols.svg` and error disappear it doesn't work the same.

**How to?**

**Comment by ivanvotti** [comment]
Yeah Windows support is still in progress. I'll take a look when I have time. BTW, everything works on MacOS and Linux.

**Comment by hyjk2000** [comment]
When built on Windows, the injected script that loads the SVG sprite is using `\` instead of `/` in the path, that's why it won't load the sprite file as expected.

```html
<script>
// ...
ajax.open('GET', '\assets\symbols.svg', true);
// ...
</script>
```

Apart from this, everything else seems to be working just fine.
