### ISSUE TITLE
Viewer doesn't work when fingerprinting for ".json" is enabled

### ISSUE THREAD

**Issue by Davidhidalgo** [ivanvotti/ember-svg-jar#54]
With:
fingerprint: {
      enabled: true,
}
on `ember-cli-build.js`, svg-jar viewer page is trying to load the file with the fingerprint (like `svg-jar-5aaba2f0819df980dd1e5a835456e821.json`, but the viewer builder creates: `svg-jar.json`

**Comment by ivanvotti** [comment]
You could add it to the `exclude` array like so:

```js
  fingerprint: {
    exclude: ['svg-jar.json'],
    ...
  }
```

Please close the issue if it works for you.

**Comment by Davidhidalgo** [comment]
This doesn't work. I thinks is because the builder is creating the file on the build.

**Comment by ivanvotti** [comment]
Can you post your `ember-cli-build.js` or its part?

**Comment by Davidhidalgo** [comment]
Sure!
```
{
    fingerprint: {
      enabled: true,
      exclude: [
        'svg-jar.json'
      ]
    },
    outputPaths: {
      app: {
        css: {
          'common-styles-for-django': 'common.css'
        }
      }
    },
    svgJar: {
      sourceDirs: ['public/assets/icons']
    }
}
```

**Comment by ivanvotti** [comment]
It looks like it's a bug of `fingerprint`. Anyway you could add something like this and it should work:

```js
    fingerprint: {
      enabled: true,
      extensions: ['json', 'js', 'css', 'png', 'jpg', 'gif', 'map']
    },
```

**Comment by Davidhidalgo** [comment]
Thanks @ivanvotti! Works perfectly! :)
