### ISSUE TITLE
Make addon consumable without build step / as Git dependency

### ISSUE THREAD

**Issue by buschtoens** [ivanvotti/ember-svg-jar#55]
I am very much looking forward to get to use #52 in production. So much in fact, that I have been using a  [private fork](https://github.com/buschtoens/ember-svg-jar/tree/better-addon-support) for quite some time now, since there has been no official release so far. The point of this issue is not to pressure you into cutting a new release.

The reason I'm opening this issue, is this diff https://github.com/buschtoens/ember-svg-jar/commit/a9b6f76178eb69d5caacf32b36a5949f1e4e48c0

```diff
 /* eslint-env node */
 
-module.exports = require('./lib/index');
+module.exports = require('./src/index');
```

Because of this build step here:

https://github.com/ivanvotti/ember-svg-jar/blob/bbec727607a7f0f80f82ea2a5692079a1050b63a/package.json#L24

To be able to use this addon as a direct Git dependency, which is useful for trying out unreleased features or fixes, you either have to apply the above patch or push a built version.

Since you're not using any ES features that aren't natively supported on the latest version of Node, enabling direct, untranspiled usage is no problem.

I think the cleanest solution is to add a symlink `lib/index.js` to `src/index.js` or a js file that re-exports `src/index.js` for maximum OS compatibility, and then remove that file during the build step.

Would you accept such a PR?

**Comment by ivanvotti** [comment]
Sounds good. It would be great to have such a PR. I'm going to release in a few days.

**Comment by ivanvotti** [comment]
It's done. The addon can be consumable without the build step as Git dependency.
