### ISSUE TITLE
Module Unification Incompatibilities

### ISSUE THREAD

**Issue by rwjblue** [ivanvotti/ember-svg-jar#56]
This addon has a `src/` folder (which it uses for "node land things"), but as of ember-cli@3.2 (current master version of ember-cli) an addon having a `src/` folder means it is opting in to [Module Unification](https://github.com/emberjs/rfcs/blob/master/text/0143-module-unification.md).
 
There are a few options that I've listed here, but there definitely may be more that I've not thought of yet:

1. Move the src/ files to some other directory.
2. Change the detection that ember-cli does so that this assumption that `src/` existing means the addon is using the new module layout is less likely to be breaking for addons (like this one) that already use the `src/` folder.
3. Update this addon to implement `isModuleUnification` method that always returns `false`.
4. Override the `this.treePaths.src` to point to another folder (other than `src/`).

---

I'm mostly only filing this issue because this addon is incompatible with ember-cli#master branch, and I'd like to figure out a nice path forward before users start getting trolled...

**Comment by ivanvotti** [comment]
Fixed in master.
