### ISSUE TITLE
missing viewBox warning

### ISSUE THREAD

**Issue by lukemelia** [ivanvotti/ember-svg-jar#57]
We have an svg we are using as a border that we don't want to have a viewBox (because we don't want it to scale, but rather to fill the available space without scaling the border size).

This works fine. However, the addon emits a warning:

```
WARNING: [ember-svg-jar][inline] SVG files without viewBox found:
Path: bordered-rectangle.svg
```

There doesn't seem to be any way to suppress the warning.

**Comment by ivanvotti** [comment]
Now you can suppress the warning like this:
```javascript
{
  svgJar: {
    validations: {
      validateViewBox: false
    }
  }
}
```
https://github.com/ivanvotti/ember-svg-jar/blob/master/docs/configuration.md#validations

**Comment by lukemelia** [comment]
Terrific. Thanks Ivan!

**Comment by lukemelia** [comment]
We're looking forward to a release with this change when you have a chance! 😄

**Comment by ivanvotti** [comment]
@lukemelia Done. https://github.com/ivanvotti/ember-svg-jar/blob/master/CHANGELOG.md#v100
