### ISSUE TITLE
Missing inline SVG error

### ISSUE THREAD

**Issue by Macxim** [ivanvotti/ember-svg-jar#59]
Hi, thanks for your work.
I can't seem to get this to work though.

I get the following error: 

`ember-svg-jar: Missing inline SVG for icon-paper-plane`

My config in `ember-cli-build.js` is the following:

```js
    svgJar: {
      strategy: 'symbol',
      symbol: {
        sourceDirs: ['app/icons'],
        prefix: 'icon-'
      },
      optimizer : {
        plugins: [
          { cleanupAttrs: true },
          { removeDoctype: true },
          { removeXMLProcInst: true },
          { removeComments: true },
          { removeMetadata: true },
          { removeTitle: true },
          { removeDesc: true },
          { removeUselessDefs: true },
          { removeEditorsNSData: true },
          { removeEmptyAttrs: true },
          { removeHiddenElems: true },
          { removeEmptyText: true },
          { removeEmptyContainers: true },
          { removeViewBox: false },
          { cleanUpEnableBackground: true },
          { convertStyleToAttrs: true },
          { convertColors: true },
          { convertPathData: true },
          { convertTransform: true },
          { removeUnknownsAndDefaults: true },
          { removeNonInheritableGroupAttrs: true },
          { removeUselessStrokeAndFill: true },
          { removeUnusedNS: true },
          { cleanupIDs: true },
          { cleanupNumericValues: true },
          { moveElemsAttrsToGroup: true },
          { moveGroupAttrsToElems: true },
          { collapseGroups: true },
          { removeRasterImages: false },
          { mergePaths: true },
          { convertShapeToPath: true },
          { sortAttrs: true },
          { transformsWithOnePath: false },
          { removeDimensions: true },
          { removeAttrs: {attrs: '(stroke|fill)'} }
        ]
      }
    }
```
My SVG icon looks like this:

```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24" height="24" viewBox="0 0 24 24">
  <defs>
    <path id="paper-plane-a" d="M0,12.8125 L5.25,14.78125 L7.875,22 L11.6300625,16.98625 L18.375,19.375 L21,1 L0,12.8125 Z M9.62104261,15.7634199 L8.42180433,19 L7,14.9389711 L18,5 L9.62104261,15.7634199 Z"/>
  </defs>
  <g fill="none" fill-rule="evenodd">
    <use fill="#000" fill-rule="nonzero" xlink:href="#paper-plane-a"/>
  </g>
</svg>

```

And the generated`symbols.svg` file, that seems to be loaded properly (status 200 or 304), looks like this:

```xml
<svg style="position: absolute; width: 0; height: 0;" width="0" height="0" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" data-ember-extension="1">
<symbol id="icon-paper-plane" viewBox="0 0 24 24"><defs><path id="a" d="M0 12.813l5.25 1.968L7.875 22l3.755-5.014 6.745 2.389L21 1 0 12.813zm9.621 2.95L8.421 19 7 14.939 18 5 9.621 15.763z"/></defs><use fill-rule="nonzero" xlink:href="#a"/></symbol>
</svg>
```

In my template I'm calling the icon this way:
```
{{svg-jar "icon-paper-plane"}}
```

Nothing is displayed. What am I missing?

**Comment by ivanvotti** [comment]
For the symbol strategy, you just need to add `#` to the icon name like this: `{{svg-jar "#icon-paper-plane"}}`. Or just use the viewer where that will be done for your automatically: http://localhost:4200/ember-svg-jar/index.html

**Comment by Macxim** [comment]
Oh, good to know. I don't think I saw that anywhere in the documentation.

It might be good to add it as I didn't use the viewer (I haven't been able to make it work either 😓), it looks cool though. It throws a 404 because we have a different configuration compared to the regular setup.

Anyway, I switched to the inline strategy for the moment, it might offer more flexibility to style icons the way I want.

**Comment by ivanvotti** [comment]
Added a note about the symbol strategy helper variety: https://github.com/ivanvotti/ember-svg-jar#helper
What is your configuration? I could make it easier to setup the viewer in cases like yours.

**Comment by Macxim** [comment]
Hi, thanks for adding a note.
In our case, Ember is being served and routed through rails locally, so the address is something like: `dev.xxxx.local:3000`.
I tried with `http://dev.xxxx.local:3000/ember-svg-jar/index.html` but it renders a 404 inside the app.

**Comment by ivanvotti** [comment]
I need more context/configs. I started the ember server like this: `$ ember serve --port 3000 --host dev.xxx.local` and I was still able to access the ember app and the viewer `http://dev.xxx.local:3000/ember-svg-jar/index.html`.

**Comment by Macxim** [comment]
We serve ember through [`ember-cli-rails`](https://github.com/thoughtbot/ember-cli-rails). I’m not sure we could expose the SVG viewer.
