### ISSUE TITLE
Add option to enable ember-svg-jar in production

### ISSUE THREAD

**Issue by nizarayari** [ivanvotti/ember-svg-jar#74]
Hi there, I'm deploying my addon with github pages. Is there a way to enable ember-svg-jar in production ? Thanks in advance!

**Comment by ivanvotti** [comment]
The helper `{{svg-jar "my-icon" class="icon"}}` should perfectly work in production. Are you asking how to enable the viewer in production, so you can select SVGs?

**Comment by nizarayari** [comment]
Exactly, I was talking about the viewer, my bad! Thanks a lot 👍
