### ISSUE TITLE
Option to pass svg path into the prefixID plugin?

### ISSUE THREAD

**Issue by harrisjose** [ivanvotti/ember-svg-jar#85]
The prefixIDs plugin in svgo accepts a [path option](https://github.com/svg/svgo/blob/master/plugins/prefixIds.js#L137) passed into it via the options object in the `optimize` method. Examples [here](https://github.com/svg/svgo/blob/master/examples/test.js#L85) and [here](https://github.com/harrisjose/ember-inline-svg/blob/master/svg-optimizer.js#L44).

This is very useful in cases when a lot of the svgs in a project are exported from Adobe Illustrator and have classes like `st0`, `st1`. All the svgs have the same classes and the styles get messed up because of this.

Prefixing the svg classes with the relative paths is a nice way to ensure this does not happen. I guess the same could be acheived by prefixing a random value but the path option is nicer cause it's more readable while debugging.

**Comment by harrisjose** [comment]
I'd be glad to help with a PR if you could just lay out what needs to be done both in this repo and in `brocolli-svg-optimizer`.

**Comment by ivanvotti** [comment]
It's related to solved issue #68. It can be fixed with `inlineStyles` plugin like [this](https://github.com/travis-ci/travis-web/pull/1645). Anyway, I'll take a look at the path option when I have time.

**Comment by harrisjose** [comment]
I was looking into the `inlineStyles` plugin as an alternative to this but was unsure about transitioning cause `prefixIDs` has been working very well for us.

Good to know someone else is using inlineStyles to to fix this. Thanks for the help :)

**Comment by ivanvotti** [comment]
Fixed in https://github.com/ivanvotti/broccoli-svg-optimizer/pull/11
